version: '3.8'

services:
  seed:
    build:
      context: .
      dockerfile: Dockerfile.seed
    environment:
      MONGO_URI: mongodb://mongo:27017/airO11y
    env_file:
      - .env
    networks:
      - airo11y-net
    depends_on:
      - mongo

networks:
  airo11y-net:
    external: true

